[workspace]
members = [
  "games/*",
]

default-members = ["games/ascii_snake", "games/snake", "games/sprites_example"]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.89"

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "deny"
